### ISSUE TITLE
Unhanded error event when server is already running on port

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#232]
It would be nice to handle this error and warn the user that the server is running somewhere else. 

Output:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::43711
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 Program node app.js -dev no-html-validator exited with code 1
```

**Comment by siuster95** [comment]
Currently working on it. My work for this will be on the killValidator 100% branch
