### ISSUE TITLE
Previously started app that has been moved crashes when restarted

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#800]
```
> npm run dev

> my-roosevelt-sample-app@0.1.0 dev my-roosevelt-sample-app
> nodemon app.js --development-mode

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js --development-mode`
💭  Starting my-roosevelt-sample-app in development mode...
✅  Detached validator found on port 48888
🎧  HTML validator listening on port 48888
⏳  Respawning a process to automatically kill the detached validator after 1 hour of inactivity
(node:20587) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, symlink 'my-roosevelt-sample-app/statics/images' -> 'my-roosevelt-sample-app/public/images'
    at Object.symlinkSync (fs.js:909:3)
    at FSR.symlinkSync (my-roosevelt-sample-app/node_modules/roosevelt/lib/tools/fsr.js:29:12)
    at params.staticsSymlinksToPublic.forEach (my-roosevelt-sample-app/node_modules/roosevelt/lib/mapRoutes.js:114:45)
    at Array.forEach (<anonymous>)
    at module.exports (my-roosevelt-sample-app/node_modules/roosevelt/lib/mapRoutes.js:98:34)
    at mapRoutes (my-roosevelt-sample-app/node_modules/roosevelt/roosevelt.js:257:39)
    at module.exports (my-roosevelt-sample-app/node_modules/roosevelt/lib/tools/buildScanner.js:44:5)
    at scanBuiltFiles (my-roosevelt-sample-app/node_modules/roosevelt/roosevelt.js:252:42)
    at fkill.then (my-roosevelt-sample-app/node_modules/roosevelt/lib/htmlValidator.js:319:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20587) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20587) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart
```

Preferred solution would be to simply catch the error and recommend running `npm run clean` instead of trying to remake the folders/symlinks.

**Comment by kethinov** [comment]
closed via https://github.com/rooseveltframework/roosevelt/pull/832
