### ISSUE TITLE
Node 15 breaks stuff when running npm i

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#975]
```
npm i
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> roosevelt@0.19.3 postinstall
> node ./lib/scripts/configAuditor.js && node ./lib/scripts/deprecationCheck.js

node:internal/validators:123
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:258:15)
    at validateString (node:internal/validators:123:11)
    at Object.join (node:path:1039:7)
    at configAudit (roosevelt/lib/scripts/configAuditor.js:28:35)
    at Object.<anonymous> (roosevelt/lib/scripts/configAuditor.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code 1
npm ERR! path roosevelt
npm ERR! command failed
npm ERR! command sh -c node ./lib/scripts/configAuditor.js && node ./lib/scripts/deprecationCheck.js
```

**Comment by Autre31415** [comment]
I suspect that crash is caused by [this line](https://github.com/rooseveltframework/roosevelt/blob/e0386292eb0a441528e4cfe049b5c71f3087d054/lib/scripts/deprecationCheck.js#L7), specifically the `process.env.INIT_CWD` portion of it. Perhaps node 15 deprecated that variable?

**Comment by lannonbr** [comment]
Yep @Autre31415 is correct. I found an issue [here](https://github.com/npm/cli/issues/2033) in the NPM CLI that the `INIT_CWD` environment variable is no longer being set as of NPM 7.0.
